class DossierDecorator < ApplicationDecorator
  decorates :dossier

  def link_to_add_comment
    h.link_to "#dossier_#{dossier.id}_comments", class: "btn btn-small", "data-toggle"  => "modal" do
      h.safe_concat "<i class='icon-plus'></i>" + "\nAjouter commentaire"
    end
  end

  def date_deces
    handle_none dossier.date_deces do
      localize_date(dossier.date_deces)
    end
  end
  # Accessing Helpers
  #   You can access any helper via a proxy
  #
  #   Normal Usage: helpers.number_to_currency(2)
  #   Abbreviated : h.number_to_currency(2)
  #
  #   Or, optionally enable "lazy helpers" by including this module:
  #     include Draper::LazyHelpers
  #   Then use the helpers with no proxy:
  #     number_to_currency(2)

  # Defining an Interface
  #   Control access to the wrapped subject's methods using one of the following:
  #
  #   To allow only the listed methods (whitelist):
  #     allows :method1, :method2
  #
  #   To allow everything except the listed methods (blacklist):
  #     denies :method1, :method2

  # Presentation Methods
  #   Define your own instance methods, even overriding accessors
  #   generated by ActiveRecord:
  #
  #   def created_at
  #     h.content_tag :span, time.strftime("%a %m/%d/%y"),
  #                   :class => 'timestamp'
  #   end
end
