defaults:  &defaults
  host: localhost

development:
  database: toxportal_development

test:  &TEST
  <<:  *defaults
  database: toxportal_test

cucumber:
  <<:  *TEST

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
